### ISSUE TITLE
all-repos-clone doesn't respect default branch

### ISSUE THREAD

**Issue by sloria** [asottile/all-repos#67] opened 2019-01-15 05:37 UTC
I tried running a `--dry-run` of https://github.com/asottile/all-repos-incantations#travis-remove-sudo , but it's not being applied to all cloned repos.

I'm trying to apply it to all repos in https://github.com/marshmallow-code.

I'm using the following config

```json

{
    "output_dir": ".",
    "source": "all_repos.source.github_org",
    "source_settings":  {
        "api_key": "snip",
        "org": "marshmallow-code"
    },
    "push": "all_repos.push.github_pull_request",
    "push_settings": {
        "api_key": "snip",
        "username": "sloria"
    }
}
```

But it's only being applied to three repos (that I didn't create): apispec-webframeworks, django-rest-marshmallow, marshmallow-oneofschema. 

I've verified that all the org's repos are in `repos.json` and `repos_filtered.json`

```python
marshmallow-code ❯ cat repos.json | jq
{
  "marshmallow-code/marshmallow": "git@github.com:marshmallow-code/marshmallow",
  "marshmallow-code/webargs": "git@github.com:marshmallow-code/webargs",
  "marshmallow-code/flask-marshmallow": "git@github.com:marshmallow-code/flask-marshmallow",
  "marshmallow-code/apispec": "git@github.com:marshmallow-code/apispec",
  "marshmallow-code/marshmallow-sqlalchemy": "git@github.com:marshmallow-code/marshmallow-sqlalchemy",
  "marshmallow-code/marshmallow-validators": "git@github.com:marshmallow-code/marshmallow-validators",
  "marshmallow-code/django-rest-marshmallow": "git@github.com:marshmallow-code/django-rest-marshmallow",
  "marshmallow-code/marshmallow-jsonapi": "git@github.com:marshmallow-code/marshmallow-jsonapi",
  "marshmallow-code/marshmallow-oneofschema": "git@github.com:marshmallow-code/marshmallow-oneofschema",
  "marshmallow-code/marshmallow-select": "git@github.com:marshmallow-code/marshmallow-select",
  "marshmallow-code/apispec-webframeworks": "git@github.com:marshmallow-code/apispec-webframeworks"
}

~/projects/marshmallow-code
marshmallow-code ❯ cat repos_filtered.json | jq
{
  "marshmallow-code/marshmallow": "git@github.com:marshmallow-code/marshmallow",
  "marshmallow-code/webargs": "git@github.com:marshmallow-code/webargs",
  "marshmallow-code/flask-marshmallow": "git@github.com:marshmallow-code/flask-marshmallow",
  "marshmallow-code/apispec": "git@github.com:marshmallow-code/apispec",
  "marshmallow-code/marshmallow-sqlalchemy": "git@github.com:marshmallow-code/marshmallow-sqlalchemy",
  "marshmallow-code/marshmallow-validators": "git@github.com:marshmallow-code/marshmallow-validators",
  "marshmallow-code/django-rest-marshmallow": "git@github.com:marshmallow-code/django-rest-marshmallow",
  "marshmallow-code/marshmallow-jsonapi": "git@github.com:marshmallow-code/marshmallow-jsonapi",
  "marshmallow-code/marshmallow-oneofschema": "git@github.com:marshmallow-code/marshmallow-oneofschema",
  "marshmallow-code/marshmallow-select": "git@github.com:marshmallow-code/marshmallow-select",
  "marshmallow-code/apispec-webframeworks": "git@github.com:marshmallow-code/apispec-webframeworks"
}

```

Any idea why it's not finding all the repos?

**Comment by asottile** [comment] 2019-01-15 05:49
only three of the repos contain `sudo:` in the `.travis.yml` maybe?

```console
$ all-repos-grep --repos sudo -- .travis.yml
./marshmallow-code/apispec-webframeworks
./marshmallow-code/django-rest-marshmallow
./marshmallow-code/marshmallow-oneofschema

$ all-repos-grep sudo -- .travis.yml
./marshmallow-code/apispec-webframeworks:.travis.yml:sudo: false
./marshmallow-code/apispec-webframeworks:.travis.yml:    sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
./marshmallow-code/apispec-webframeworks:.travis.yml:    sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
./marshmallow-code/django-rest-marshmallow:.travis.yml:sudo: false
./marshmallow-code/marshmallow-oneofschema:.travis.yml:sudo: false
./marshmallow-code/marshmallow-oneofschema:.travis.yml:# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
./marshmallow-code/marshmallow-oneofschema:.travis.yml:      sudo: true
```

**Comment by sloria** [comment] 2019-01-15 13:53
No, all the repos have `sudo: false` somewhere in their .travis.yml.

Turns out, all but those three repos are empty after being cloned with `all-repos-clone`.

The problem is that the repos use `dev` as the default branch instead of `master`. `all-repos-clone` tries to pull from master

```
...
fatal: Couldn't find remote ref refs/heads/master
Error fetching output/marshmallow-code/flask-marshmallow
fatal: Couldn't find remote ref refs/heads/master
Error fetching output/marshmallow-code/marshmallow
fatal: Couldn't find remote ref refs/heads/master
Error fetching output/marshmallow-code/webargs
fatal: Couldn't find remote ref refs/heads/master
Error fetching output/marshmallow-code/marshmallow-validators
fatal: Couldn't find remote ref refs/heads/master
Error fetching output/marshmallow-code/marshmallow-sqlalchemy
fatal: Couldn't find remote ref refs/heads/master
Error fetching output/marshmallow-code/apispec
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (44/44), done.
fatal: Couldn't find remote ref refs/heads/master
...
```

`all_repos.clone` appears to be hardcoding the `master` branch when initializing repos.

https://github.com/asottile/all-repos/blob/ddb482a65726589252e806e9c9ff6580b9177dd5/all_repos/clone.py#L66

Perhaps the code could fetch the default branch instead? Looks like it's available through the GitHub API:

```
marshmallow-code ❯ http https://api.github.com/repos/marshmallow-code/marshmallow | jq '.default_branch'
"dev"
```

**Comment by asottile** [comment] 2019-01-15 15:43
Ah yes, right. This is a duplicate of #6 -- unfortunate :(

I've been meaning to fix this but as I've only hit this on one of my repos / my employers repos I haven't attempted fixing it. If you'd like to patch it that would be greatly appreciated!

**Closed by asottile** 2019-01-15 15:43 UTC
